{
 "title": "Go GC metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Total GC time vs LinkedList generation ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "go_gc_duration_seconds_sum", "legendFormat": "Total GC time" },
    { "expr": "go_linked_list_created_total", "legendFormat": "LinkedList generation " }
   ]
  },
  {
   "title": "Total GC cycles vs LinkedList generation ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "go_gc_operations_total", "legendFormat": "Total GC cycles" },
    { "expr": "go_linked_list_created_total", "legendFormat": "LinkedList generation " }
   ]
  },
  {
   "title": "Next GC bytes vs LinkedList generation ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "go_memstats_next_gc_bytes", "legendFormat": "Next GC bytes" },
    { "expr": "go_linked_list_created_total", "legendFormat": "LinkedList generation " }
   ]
  }
 ]
}